services:
  traefik:
    env_file:
      - .env.dev
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard Traefik activé en dev
    networks:
      - physigames-network
    restart: unless-stopped

  postgres:
    env_file:
      - .env.dev
    ports:
      - "${POSTGRES_PORT:-5432}:5432"  # Port exposé pour accès direct en dev
    networks:
      - physigames-network
    restart: unless-stopped

  keycloak:
    env_file:
      - .env.dev
    command: start-dev --import-realm
    environment:
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: true
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      KC_PROXY: edge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`${KEYCLOAK_HOSTNAME}`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.routers.keycloak.tls.certresolver=dev"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.keycloak-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.keycloak-headers.headers.customrequestheaders.X-Forwarded-Host=${KEYCLOAK_HOSTNAME}"
      - "traefik.http.middlewares.keycloak-headers.headers.customrequestheaders.X-Forwarded-Port=443"
      - "traefik.http.routers.keycloak.middlewares=keycloak-headers"
    networks:
      - physigames-network
    restart: unless-stopped

  physigames-app:
    env_file:
      - .env.dev
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${API_HOSTNAME}`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.tls.certresolver=dev"
      - "traefik.http.services.backend.loadbalancer.server.port=${APP_CONTAINER_PORT}"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JPA_SHOW_SQL: true
      LOGGING_LEVEL_ROOT: DEBUG
    networks:
      - physigames-network
    restart: unless-stopped

networks:
  physigames-network:
    driver: bridge
