api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: physigames-network
    watch: true

log:
  level: INFO
  filePath: "/var/log/traefik/traefik.log"

accessLog:
  filePath: "/var/log/traefik/access.log"

certificatesResolvers:
  production:
    acme:
      email: prod@physigames.fr
      storage: /ssl-certs/acme.json
      dnsChallenge:
        provider: ovh
  dev:
    acme:
      email: dev@physigames.fr
      storage: /ssl-certs/acme.json
      dnsChallenge:
        provider: ovh