-- V10__Insert_Localized_Genres_fr.sql
-- Insère les traductions françaises des genres dans `localized_genres` pour le langage 'fr-fr'.
-- Idempotent : n'insère que les paires (genre, langue) manquantes.

INSERT INTO localized_genres (genre_id, language_id, name)
SELECT g.id, l.id, v.name
FROM (VALUES
('Action','Action'),
('Platformer','Plate-forme'),
('BeatEmUp','Beat ''em up'),
('Brawler','Brawler'),
('HackAndSlash','Hack ''n'' Slash'),
('Shooter','Shooter'),
('FPS','FPS'),
('TPS','TPS'),
('TwinStick','Twin-stick'),
('RunAndGun','Run and Gun'),
('Stealth','Discrétion'),
('Infiltration','Infiltration'),
('ActionAdventure','Action-Aventure'),
('Adventure','Aventure'),
('PointAndClick','Point & Click'),
('WalkingSimulator','Walking Simulator'),
('InteractiveFiction','Fiction interactive'),
('VisualNovel','Visual Novel'),
('EscapeGame','Escape Game'),
('PuzzleAdventure','Puzzle-Aventure'),
('RPG','RPG'),
('JRPG','JRPG'),
('WRPG','WRPG'),
('ActionRPG','Action-RPG'),
('TacticalRPG','Tactique-RPG'),
('StrategyRPG','Stratégie-RPG'),
('DungeonCrawler','Dungeon Crawler'),
('Roguelike','Roguelike'),
('Roguelite','Roguelite'),
('MMORPG','MMORPG'),
('Simulation','Simulation'),
('LifeSim','Simulation de vie'),
('FlightSim','Simulation de vol'),
('MilitarySim','Simulation militaire'),
('DrivingSim','Simulation de conduite'),
('RacingSim','Simulation de course'),
('CityBuilder','City Builder'),
('Tycoon','Tycoon'),
('BusinessSim','Simulation d''entreprise'),
('FarmingSim','Simulation agricole'),
('ImmersiveSim','Simulation immersive'),
('Strategy','Stratégie'),
('RTS','RTS'),
('TBS','TBS'),
('4X','4X'),
('TowerDefense','Tower Defense'),
('MOBA','MOBA'),
('AutoBattler','Auto Battler'),
('Racing','Course'),
('ArcadeRacing','Course arcade'),
('Sports','Sports'),
('TraditionalSports','Sports traditionnels'),
('ExtremeSports','Sports extrêmes'),
('Esports','Esport'),
('Puzzle','Puzzle'),
('LogicPuzzle','Puzzle logique'),
('PhysicsPuzzle','Puzzle physique'),
('NarrativePuzzle','Puzzle narratif'),
('WordGame','Jeu de mots'),
('NumberGame','Jeu de nombres'),
('Horror','Horreur'),
('SurvivalHorror','Horreur de survie'),
('PsychologicalHorror','Horreur psychologique'),
('ActionHorror','Horreur d''action'),
('AsymmetricalHorror','Horreur asymétrique'),
('PartyGame','Party Game'),
('MusicGame','Jeu musical'),
('RhythmGame','Jeu de rythme'),
('Quiz','Quiz'),
('Trivia','Trivia'),
('Educational','Éducatif'),
('Metroidvania','Metroidvania'),
('BattleRoyale','Battle Royale'),
('Sandbox','Sandbox'),
('OpenWorld','Monde ouvert'),
('Soulslike','Soulslike'),
('Survival','Survie'),
('Crafting','Artisanat'),
('Building','Construction'),
('NarrativeDriven','Narratif'),
('ChoiceBased','Basé sur les choix'),
('IdleGame','Idle Game'),
('Incremental','Incrémental'),
('Gacha','Gacha'),
('HyperCasual','Hyper Casual')
) AS v(code, name)
JOIN genres g ON g.code = v.code
JOIN languages l ON l.code = 'fr-fr'
WHERE NOT EXISTS (
    SELECT 1 FROM localized_genres lg WHERE lg.genre_id = g.id AND lg.language_id = l.id
);

