CREATE TABLE images
(
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    localized_physical_release_id BIGINT                                  NOT NULL,
    url                           VARCHAR(255),
    CONSTRAINT pk_images PRIMARY KEY (id)
);

ALTER TABLE localized_physical_releases
    ADD box_image_id BIGINT;

ALTER TABLE localized_physical_releases
    ADD CONSTRAINT uc_localized_physical_releases_box_image UNIQUE (box_image_id);

ALTER TABLE images
    ADD CONSTRAINT FK_IMAGES_ON_LOCALIZED_PHYSICAL_RELEASE FOREIGN KEY (localized_physical_release_id) REFERENCES localized_physical_releases (id);

ALTER TABLE localized_physical_releases
    ADD CONSTRAINT FK_LOCALIZED_PHYSICAL_RELEASES_ON_BOX_IMAGE FOREIGN KEY (box_image_id) REFERENCES images (id);

ALTER TABLE localized_physical_releases
    DROP COLUMN box_image;