CREATE TABLE regions
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code VARCHAR(255)                            NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_regions PRIMARY KEY (id)
);

ALTER TABLE physical_releases
    ADD region_id BIGINT;

ALTER TABLE regions
    ADD CONSTRAINT uc_regions_code UNIQUE (code);

ALTER TABLE physical_releases
    ADD CONSTRAINT FK_PHYSICAL_RELEASES_ON_REGION FOREIGN KEY (region_id) REFERENCES regions (id);

INSERT INTO regions (code, name) VALUES
('PAL', 'PAL'),
('USA', 'USA'),
('ASIA', 'ASIA/JAP');
