CREATE TABLE development_studios
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_development_studios PRIMARY KEY (id)
);

CREATE TABLE game_development_studios
(
    development_studio_id BIGINT NOT NULL,
    game_id               BIGINT NOT NULL,
    CONSTRAINT pk_game_development_studios PRIMARY KEY (development_studio_id, game_id)
);

CREATE TABLE game_genres
(
    game_id  BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    CONSTRAINT pk_game_genres PRIMARY KEY (game_id, genre_id)
);

CREATE TABLE game_publishers
(
    game_id      BIGINT NOT NULL,
    publisher_id BIGINT NOT NULL,
    CONSTRAINT pk_game_publishers PRIMARY KEY (game_id, publisher_id)
);

CREATE TABLE games
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_games PRIMARY KEY (id)
);

CREATE TABLE genres
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_genres PRIMARY KEY (id)
);

CREATE TABLE publishers
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_publishers PRIMARY KEY (id)
);

ALTER TABLE game_development_studios
    ADD CONSTRAINT fk_gamdevstu_on_development_studio FOREIGN KEY (development_studio_id) REFERENCES development_studios (id);

ALTER TABLE game_development_studios
    ADD CONSTRAINT fk_gamdevstu_on_game FOREIGN KEY (game_id) REFERENCES games (id);

ALTER TABLE game_genres
    ADD CONSTRAINT fk_gamgen_on_game FOREIGN KEY (game_id) REFERENCES games (id);

ALTER TABLE game_genres
    ADD CONSTRAINT fk_gamgen_on_genre FOREIGN KEY (genre_id) REFERENCES genres (id);

ALTER TABLE game_publishers
    ADD CONSTRAINT fk_gampub_on_game FOREIGN KEY (game_id) REFERENCES games (id);

ALTER TABLE game_publishers
    ADD CONSTRAINT fk_gampub_on_publisher FOREIGN KEY (publisher_id) REFERENCES publishers (id);