CREATE TABLE editions
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code    VARCHAR(255)                            NOT NULL,
    libelle VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_editions PRIMARY KEY (id)
);

CREATE TABLE game_languages
(
    game_id     BIGINT NOT NULL,
    language_id BIGINT NOT NULL,
    CONSTRAINT pk_game_languages PRIMARY KEY (game_id, language_id)
);

CREATE TABLE languages
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code    VARCHAR(255)                            NOT NULL,
    libelle VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_languages PRIMARY KEY (id)
);

CREATE TABLE localized_physical_releases
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    physical_release_id BIGINT                                  NOT NULL,
    language_id         BIGINT                                  NOT NULL,
    box_image           VARCHAR(255),
    CONSTRAINT pk_localized_physical_releases PRIMARY KEY (id)
);

CREATE TABLE physical_releases
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    release_date date,
    edition_id   BIGINT,
    platform_id  BIGINT,
    CONSTRAINT pk_physical_releases PRIMARY KEY (id)
);

CREATE TABLE platforms
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code    VARCHAR(255)                            NOT NULL,
    libelle VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_platforms PRIMARY KEY (id)
);

ALTER TABLE editions
    ADD CONSTRAINT uc_editions_code UNIQUE (code);

ALTER TABLE languages
    ADD CONSTRAINT uc_languages_code UNIQUE (code);

ALTER TABLE platforms
    ADD CONSTRAINT uc_platforms_code UNIQUE (code);

ALTER TABLE localized_physical_releases
    ADD CONSTRAINT FK_LOCALIZED_PHYSICAL_RELEASES_ON_LANGUAGE FOREIGN KEY (language_id) REFERENCES languages (id);

ALTER TABLE localized_physical_releases
    ADD CONSTRAINT FK_LOCALIZED_PHYSICAL_RELEASES_ON_PHYSICAL_RELEASE FOREIGN KEY (physical_release_id) REFERENCES physical_releases (id);

ALTER TABLE physical_releases
    ADD CONSTRAINT FK_PHYSICAL_RELEASES_ON_EDITION FOREIGN KEY (edition_id) REFERENCES editions (id);

ALTER TABLE physical_releases
    ADD CONSTRAINT FK_PHYSICAL_RELEASES_ON_PLATFORM FOREIGN KEY (platform_id) REFERENCES platforms (id);

ALTER TABLE game_languages
    ADD CONSTRAINT fk_gamlan_on_game FOREIGN KEY (game_id) REFERENCES games (id);

ALTER TABLE game_languages
    ADD CONSTRAINT fk_gamlan_on_language FOREIGN KEY (language_id) REFERENCES languages (id);