-- V7__Insert_Genres.sql
-- Insère la liste des codes de genres dans la table `genres` (colonne `code`).
-- Version idempotente : n'insère que les codes qui n'existent pas encore.

ALTER TABLE genres
    ADD CONSTRAINT uc_genres_code UNIQUE (code);

INSERT INTO genres (code)
SELECT v.code
FROM (VALUES
('Action'),
('Platformer'),
('BeatEmUp'),
('Brawler'),
('HackAndSlash'),
('Shooter'),
('FPS'),
('TPS'),
('TwinStick'),
('RunAndGun'),
('Stealth'),
('Infiltration'),
('ActionAdventure'),
('Adventure'),
('PointAndClick'),
('WalkingSimulator'),
('InteractiveFiction'),
('VisualNovel'),
('EscapeGame'),
('PuzzleAdventure'),
('RPG'),
('JRPG'),
('WRPG'),
('ActionRPG'),
('TacticalRPG'),
('StrategyRPG'),
('DungeonCrawler'),
('Roguelike'),
('Roguelite'),
('MMORPG'),
('Simulation'),
('LifeSim'),
('FlightSim'),
('MilitarySim'),
('DrivingSim'),
('RacingSim'),
('CityBuilder'),
('Tycoon'),
('BusinessSim'),
('FarmingSim'),
('ImmersiveSim'),
('Strategy'),
('RTS'),
('TBS'),
('4X'),
('TowerDefense'),
('MOBA'),
('AutoBattler'),
('Racing'),
('ArcadeRacing'),
('Sports'),
('TraditionalSports'),
('ExtremeSports'),
('Esports'),
('Puzzle'),
('LogicPuzzle'),
('PhysicsPuzzle'),
('NarrativePuzzle'),
('WordGame'),
('NumberGame'),
('Horror'),
('SurvivalHorror'),
('PsychologicalHorror'),
('ActionHorror'),
('AsymmetricalHorror'),
('PartyGame'),
('MusicGame'),
('RhythmGame'),
('Quiz'),
('Trivia'),
('Educational'),
('Metroidvania'),
('BattleRoyale'),
('Sandbox'),
('OpenWorld'),
('Soulslike'),
('Survival'),
('Crafting'),
('Building'),
('NarrativeDriven'),
('ChoiceBased'),
('IdleGame'),
('Incremental'),
('Gacha'),
('HyperCasual')
) AS v(code)
WHERE NOT EXISTS (SELECT 1 FROM genres g WHERE g.code = v.code);

